/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButtons: typeof import('./src/components/route/ActionButtons.vue')['default']
    BottomMenu: typeof import('./src/components/navigation/BottomMenu.vue')['default']
    CreateBoulderDialog: typeof import('./src/components/route/CreateBoulderDialog.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DifficultyTag: typeof import('./src/components/route/DifficultyTag.vue')['default']
    RouteEdit: typeof import('./src/components/route/RouteEdit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteView: typeof import('./src/components/route/RouteView.vue')['default']
    SideMenu: typeof import('./src/components/navigation/SideMenu.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
